### ISSUE TITLE
CoffeeScript and globals

### ISSUE THREAD

**Issue by ghost** [DiscoverMeteor/Microscope#173]
Hi guys,

Question about this bit:

> In Meteor, the var keyword limits the scope of an object to the current file. Here, we want to make the Posts collection available to our whole app, which is why we're not using the var keyword.

But if I were to translate the blow line into CoffeeScript:

```
Posts = new Mongo.Collection('posts');
```

It would be:

```
Posts = new Mongo.Collection 'posts'
```

Which would compile back into:

```
var Posts;
Posts = new Mongo.Collection('posts');
```

So is this an issue in Meteor? Do I need to do something special to make sure `Posts` is available globally? Maybe this:

```
window.Posts = new Mongo.Collection 'posts'
```

**Comment by castlefields** [comment]
@CaptSaltyJack I'm just starting with Angular Meteor using Jade and Coffeescript. The above also solved my issue.

What have your experiences been with Meteor / Coffeescript - a Rocky Road or Plain Sailing ?

**Comment by CaptSaltyJack** [comment]
Hey @castlefields 

CoffeeScript is great in Meteor, no issues! Just be sure to use `@` (which evaluates to `this.`) before variables to make them global. Also, using `=>` for function definitions can be handy as it eliminates the need to put `this` in a variable in order to reference it within a deeper function, i.e. instead of this in Javascript:

```javascript
var template = this;

this.someFunction({
  template.doThing();
});
```

You can simply do:

```coffeescript
@someFunction =>
  @doThing()
```

If you want to see what any CoffeeScript compiles to, just go to http://coffeescript.org/ and click "Try CoffeeScript" and type in some code. Or, in a shell you can type `coffee -bsp` and paste some code, then hit `Ctrl-D`.

**Comment by castlefields** [comment]
@CaptSaltyJack Thanx for the pointers !!
