### ISSUE TITLE
Load More to infinite

### ISSUE THREAD

**Issue by doubletaketech** [DiscoverMeteor/Microscope#206]
In your pagination example, how do I replace the "load more" button approach  with infinite scroll? 

Thanks,
Don

**Comment by tmeasday** [comment]
Hi @doubletaketech - conceptually it's pretty simple, instead of waiting for a click on the load more button, you just trigger the same behaviour when the user's scroll position is near the bottom of the page.

As always there are complexities, but this article should help you get started: https://gentlenode.com/journal/meteor-21-pagination-system-with-infinite-scroll/43

**Comment by doubletaketech** [comment]
Thank you.  I figured it out back in Feb using some of these related posts.  Thanks for the follow up.

Don
