### ISSUE TITLE
Chapter 7 Typo

### ISSUE THREAD

**Issue by eriklacson** [DiscoverMeteor/Microscope#222]
return missing in the following code for post_submit.js:
--------------------------------------------------------------------------

```
Template.postSubmit.events({
  'submit form': function(e) {
    e.preventDefault();

    var post = {
      url: $(e.target).find('[name=url]').val(),
      title: $(e.target).find('[name=title]').val()
    };

    Meteor.call('postInsert', post, function(error, result) {
      // display the error to the user and abort
      if (error)
        return alert(error.reason);

      // show this result but route anyway
      if (result.postExists)
      return  alert('This link has already been posted');

      Router.go('postPage', {_id: result._id});  
    });
  }
});
```

**Comment by SachaG** [comment]
The reason why there's a `return` in `return alert(error.reason);` is because we want to stop the function here and not execute the rest of the code block. 

For the second `alert` on the other hand, we don't want to stop code execution otherwise `Router.go` wouldn't get executed. So there's no `return` there on purpose.

**Comment by eriklacson** [comment]
Sorry about that. Thanks for clarifying. CheerS
